# Generated by Django 4.2.16 on 2024-12-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Geeks',
            new_name='GeeksModel',
        ),
    ]
