# Generated by Django 4.2.16 on 2024-12-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0003_geeksmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='id_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
