# Generated by Django 4.2.16 on 2024-12-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfg', '0004_geeksmodel_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gfgs'),
        ),
    ]
